name: go CI

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Build Binary
        run: |
          mkdir -p bibary
          go build -o binary/dummy-server.bin ./cmd
      - name: Simple Test
        run: |
          ./binary/dummy-server.bin &
          sleep 3
          curl -v http://localhost:8888
          kill $!
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: binary
          path: binary/dummy-server.bin
          retention-days: 30 
